# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendAmail', '0002_auto_20180326_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmodel',
            old_name='subject',
            new_name='message',
        ),
    ]
