# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendAmail', '0003_auto_20180327_1116'),
    ]

    operations = [
    ]
