# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendAmail', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='userprofile',
        ),
    ]
